name = "fenomen-io"
main = "src/index.ts"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "USERS_KV"
id = "c831039855564c16818cfcd988140723"

[vars]
ENVIRONMENT = "development"
JWT_SECRET = "Q2xvdWRmbGFyZVNlY3JldEtleUhlcmUxMjM0NTY3ODkwMTIzNDU2Nzg5MA=="

