name = "fenomen-app"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[[kv_namespaces]]
binding = "fenomen-io-users"
id = "c831039855564c16818cfcd988140723"  # wrangler kv:namespace create "USERS_KV" komutuyla oluşturun

# Production için preview namespace (opsiyonel)
# preview_id = "BURAYA-PREVIEW-KV-ID"

